DROP POLICY IF EXISTS law_engine_phase5_final_admin_delete ON public.law_engine_phase5_finalization_audit;
DROP POLICY IF EXISTS law_engine_phase5_final_self_insert ON public.law_engine_phase5_finalization_audit;
DROP POLICY IF EXISTS law_engine_phase5_final_self_select ON public.law_engine_phase5_finalization_audit;
DROP TABLE IF EXISTS public.law_engine_phase5_finalization_audit;
