apiVersion: v1
kind: ResourceQuota
metadata:
  name: iterlaw-data-quota
  namespace: iterlaw-data
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
