apiVersion: v1
kind: ResourceQuota
metadata:
  name: iterlaw-data-quota
  namespace: iterlaw-data
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
    persistentvolumeclaims: "4"
