name: Manual Deploy Azure Functions

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f -name "package.json"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build if available
        run: npm run build --if-present

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: iterlaw-api-001
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
