apiVersion: v1
kind: ResourceQuota
metadata:
  name: iterlaw-ai-quota
  namespace: iterlaw-ai
spec:
  hard:
    pods: "20"
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
